name: qr_codee_scannerr
description: A QR Code Scanner Application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  mobile_scanner: ^5.2.1 # Replaced qr_code_scanner
  permission_handler: ^11.0.0
  url_launcher: ^6.1.10
  shared_preferences: ^2.0.15
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true